export var DROP_ON_ITEM_OPTIONS;
(function (DROP_ON_ITEM_OPTIONS) {
    DROP_ON_ITEM_OPTIONS[DROP_ON_ITEM_OPTIONS["CREATE_FOLDER"] = 0] = "CREATE_FOLDER";
    DROP_ON_ITEM_OPTIONS[DROP_ON_ITEM_OPTIONS["DIRECT_CHILD"] = 1] = "DIRECT_CHILD";
    DROP_ON_ITEM_OPTIONS[DROP_ON_ITEM_OPTIONS["FORBID"] = 2] = "FORBID";
})(DROP_ON_ITEM_OPTIONS || (DROP_ON_ITEM_OPTIONS = {}));
